FROM maven:3.5-jdk-8

#COPY target/app.jar app.jar
#EXPOSE 8083

#openjdk:8-jdk-alpine
#VOLUME /tmp
#
#COPY target/app.jar app.jar
#EXPOSE 8083
#
#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]